version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    image: ufotech/php:8.4-fpm
    working_dir: ${WORKDIR}
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
      HISTFILE: ${WORKDIR}/var/.bash_history
    volumes:
      - ./:${WORKDIR}
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_${PROJECT_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE:  ${MYSQL_DATABASE:-project_db}
      MYSQL_USER:  ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD:-pass4dbuser}
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx_${PROJECT_NAME}
    environment:
      WORKDIR: ${WORKDIR}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/configs/nginx/project.conf.template:/etc/nginx/templates/project.conf.template
      - ./var/logs/nginx:/var/log/nginx
    links:
      - php